(function(){'use strict';var f,g=[];function l(a){g.push(a);1==g.length&&f()}function m(){for(;g.length;)g[0](),g.shift()}f=function(){setTimeout(m)};function n(a){this.a=p;this.b=void 0;this.f=[];var b=this;try{a(function(a){q(b,a)},function(a){r(b,a)})}catch(c){r(b,c)}}var p=2;function t(a){return new n(function(b,c){c(a)})}function u(a){return new n(function(b){b(a)})}function q(a,b){if(a.a==p){if(b==a)throw new TypeError;var c=!1;try{var d=b&&b.then;if(null!=b&&"object"==typeof b&&"function"==typeof d){d.call(b,function(b){c||q(a,b);c=!0},function(b){c||r(a,b);c=!0});return}}catch(e){c||r(a,e);return}a.a=0;a.b=b;v(a)}}
function r(a,b){if(a.a==p){if(b==a)throw new TypeError;a.a=1;a.b=b;v(a)}}function v(a){l(function(){if(a.a!=p)for(;a.f.length;){var b=a.f.shift(),c=b[0],d=b[1],e=b[2],b=b[3];try{0==a.a?"function"==typeof c?e(c.call(void 0,a.b)):e(a.b):1==a.a&&("function"==typeof d?e(d.call(void 0,a.b)):b(a.b))}catch(h){b(h)}}})}n.prototype.g=function(a){return this.c(void 0,a)};n.prototype.c=function(a,b){var c=this;return new n(function(d,e){c.f.push([a,b,d,e]);v(c)})};
function w(a){return new n(function(b,c){function d(c){return function(d){h[c]=d;e+=1;e==a.length&&b(h)}}var e=0,h=[];0==a.length&&b(h);for(var k=0;k<a.length;k+=1)u(a[k]).c(d(k),c)})}function x(a){return new n(function(b,c){for(var d=0;d<a.length;d+=1)u(a[d]).c(b,c)})};window.Promise||(window.Promise=n,window.Promise.resolve=u,window.Promise.reject=t,window.Promise.race=x,window.Promise.all=w,window.Promise.prototype.then=n.prototype.c,window.Promise.prototype["catch"]=n.prototype.g);}());

(function(){var k=!!document.addEventListener;function l(a,b){k?a.addEventListener("scroll",b,!1):a.attachEvent("scroll",b)}function w(a){document.body?a():k?document.addEventListener("DOMContentLoaded",a):document.attachEvent("onreadystatechange",function(){"interactive"!=document.readyState&&"complete"!=document.readyState||a()})};function x(a){this.font=a;this.baseFonts=["monospace","sans-serif","serif"];this.h=document.getElementsByTagName("body")[0];this.s=document.createElement("span");this.s.setAttribute("aria-hidden","true");this.s.style.fontSize="72px";this.s.appendChild(document.createTextNode("mmmmmmmmmmlli"));this.defaultWidth={};this.defaultHeight={};for(var b in this.baseFonts)this.s.style.fontFamily=this.baseFonts[b],this.h.appendChild(this.s),this.defaultWidth[this.baseFonts[b]]=this.s.offsetWidth,this.defaultHeight[this.baseFonts[b]]=
this.s.offsetHeight,this.h.removeChild(this.s)};function y(a){this.a=document.createElement("div");this.a.setAttribute("aria-hidden","true");this.a.appendChild(document.createTextNode(a));this.b=document.createElement("span");this.c=document.createElement("span");this.i=document.createElement("span");this.f=document.createElement("span");this.g=-1;this.b.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.c.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";
this.f.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.i.style.cssText="display:inline-block;width:200%;height:200%;font-size:16px;max-width:none;";this.b.appendChild(this.i);this.c.appendChild(this.f);this.a.appendChild(this.b);this.a.appendChild(this.c)}
function z(a,b){a.a.style.cssText="max-width:none;min-width:20px;min-height:20px;display:inline-block;overflow:hidden;position:absolute;width:auto;margin:0;padding:0;top:-999px;left:-999px;white-space:nowrap;font:"+b+";"}function A(a){var b=a.a.offsetWidth,c=b+100;a.f.style.width=c+"px";a.c.scrollLeft=c;a.b.scrollLeft=a.b.scrollWidth+100;return a.g!==b?(a.g=b,!0):!1}function B(a,b){function c(){var a=h;A(a)&&null!==a.a.parentNode&&b(a.g)}var h=a;l(a.b,c);l(a.c,c);A(a)};function C(a,b){var c=b||{};this.family=a;this.style=c.style||"normal";this.weight=c.weight||"normal";this.stretch=c.stretch||"normal"}var D=null,H=null,I=!!window.FontFace;function J(){if(null===H){var a=document.createElement("div");try{a.style.font="condensed 100px sans-serif"}catch(b){}H=""!==a.style.font}return H}function K(a,b){return[a.style,a.weight,J()?a.stretch:"","100px",b].join(" ")}
function L(a){console.log(a);a=new x(a);var b=!1,c;for(c in a.baseFonts){a.s.style.fontFamily=a.font+","+a.baseFonts[c];a.h.appendChild(a.s);var h=a.s.offsetWidth!=a.defaultWidth[a.baseFonts[c]]||a.s.offsetHeight!=a.defaultHeight[a.baseFonts[c]];a.h.removeChild(a.s);b=b||h}return b}
C.prototype.a=function(a,b){var c=this,h=a||"BESbswy",E=b||3E3,F=(new Date).getTime();return new Promise(function(a,b){L(c.family)&&a(c);if(I){var q=function(){(new Date).getTime()-F>=E?b(c):document.fonts.load(K(c,c.family),h).then(function(b){1<=b.length?a(c):setTimeout(q,25)},function(){b(c)})};q()}else w(function(){function r(){var b;if(b=-1!=e&&-1!=f||-1!=e&&-1!=g||-1!=f&&-1!=g)(b=e!=f&&e!=g&&f!=g)||(null===D&&(b=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent),D=!!b&&(536>
parseInt(b[1],10)||536===parseInt(b[1],10)&&11>=parseInt(b[2],10))),b=D&&(e==t&&f==t&&g==t||e==u&&f==u&&g==u||e==v&&f==v&&g==v)),b=!b;b&&(null!==d.parentNode&&d.parentNode.removeChild(d),clearTimeout(G),a(c))}function q(){if((new Date).getTime()-F>=E)null!==d.parentNode&&d.parentNode.removeChild(d),b(c);else{var a=document.hidden;if(!0===a||void 0===a)e=m.a.offsetWidth,f=n.a.offsetWidth,g=p.a.offsetWidth,r();G=setTimeout(q,50)}}var m=new y(h),n=new y(h),p=new y(h),e=-1,f=-1,g=-1,t=-1,u=-1,v=-1,d=
document.createElement("div"),G=0;d.dir="ltr";z(m,K(c,"sans-serif"));z(n,K(c,"serif"));z(p,K(c,"monospace"));d.appendChild(m.a);d.appendChild(n.a);d.appendChild(p.a);document.body.appendChild(d);t=m.a.offsetWidth;u=n.a.offsetWidth;v=p.a.offsetWidth;q();B(m,function(a){e=a;r()});z(m,K(c,'"'+c.family+'",sans-serif'));B(n,function(a){f=a;r()});z(n,K(c,'"'+c.family+'",serif'));B(p,function(a){g=a;r()});z(p,K(c,'"'+c.family+'",monospace'))})})};window.FontFaceObserver=C;window.FontFaceObserver.prototype.check=C.prototype.a;"undefined"!==typeof module&&(module.exports=window.FontFaceObserver);}());
